{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:44:47.728Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:44:49.498Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:44:51.247Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:44:52.884Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:44:54.714Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:44:57.337Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Unknown database 'ticket_service_db'","name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'ticket_service_db'","sqlState":"42000"},"service":"ticket-service","stack":"SequelizeConnectionError: Unknown database 'ticket_service_db'\n    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async startServer (/app/src/main.js:86:5)","timestamp":"2025-06-10T11:45:01.974Z"}
{"errors":[{"instance":{"asunto":"dasda","createdAt":"2025-06-11T09:30:07.811Z","departamento":"rrhh","descripcion":"dasda","estado":"Abierto","etiquetas":[],"fechaCreacion":"2025-06-11","id":"TICK-005","prioridad":"Media","ultimaActualizacion":"2025-06-11","updatedAt":"2025-06-11T09:30:07.811Z","usuario":"Juan","usuarioEmail":"juanfrauca@outlook.com"},"message":"PRIMARY must be unique","origin":"DB","path":"PRIMARY","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":"TICK-005"}],"fields":{"PRIMARY":"TICK-005"},"level":"error","message":"Error creating ticket: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"ER_DUP_ENTRY","errno":1062,"parameters":["TICK-005","dasda","dasda","rrhh","Juan","juanfrauca@outlook.com","Media","Abierto","2025-06-11","2025-06-11","[]","2025-06-11 09:30:07","2025-06-11 09:30:07"],"sql":"INSERT INTO `tickets` (`id`,`asunto`,`descripcion`,`departamento`,`usuario`,`usuarioEmail`,`prioridad`,`estado`,`fechaCreacion`,`ultimaActualizacion`,`etiquetas`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);","sqlMessage":"Duplicate entry 'TICK-005' for key 'tickets.PRIMARY'","sqlState":"23000"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"parameters":["TICK-005","dasda","dasda","rrhh","Juan","juanfrauca@outlook.com","Media","Abierto","2025-06-11","2025-06-11","[]","2025-06-11 09:30:07","2025-06-11 09:30:07"],"sql":"INSERT INTO `tickets` (`id`,`asunto`,`descripcion`,`departamento`,`usuario`,`usuarioEmail`,`prioridad`,`estado`,`fechaCreacion`,`ultimaActualizacion`,`etiquetas`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);","sqlMessage":"Duplicate entry 'TICK-005' for key 'tickets.PRIMARY'","sqlState":"23000"},"service":"ticket-service","sql":"INSERT INTO `tickets` (`id`,`asunto`,`descripcion`,`departamento`,`usuario`,`usuarioEmail`,`prioridad`,`estado`,`fechaCreacion`,`ultimaActualizacion`,`etiquetas`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);","stack":"Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.insert (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async model.save (/app/node_modules/sequelize/lib/model.js:2490:35)\n    at async Ticket.create (/app/node_modules/sequelize/lib/model.js:1362:12)\n    at async TicketRepository.create (/app/src/repositories/ticket.repository.js:68:12)\n    at async TicketService.createTicket (/app/src/services/ticket.service.js:46:22)\n    at async createTicket (/app/src/controllers/ticket.controller.js:55:22)","timestamp":"2025-06-11T09:30:07.829Z"}
{"ip":"::ffff:172.18.0.1","level":"error","message":"Error al crear el ticket","method":"POST","path":"/api/tickets","service":"ticket-service","stack":"Error: Error al crear el ticket\n    at TicketService.createTicket (/app/src/services/ticket.service.js:63:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async createTicket (/app/src/controllers/ticket.controller.js:55:22)","statusCode":500,"timestamp":"2025-06-11T09:30:07.835Z"}
{"errors":[{"instance":{"asunto":"dasda","createdAt":"2025-06-11T09:30:24.341Z","departamento":"rrhh","descripcion":"dasda","estado":"Abierto","etiquetas":[],"fechaCreacion":"2025-06-11","id":"TICK-005","prioridad":"Media","ultimaActualizacion":"2025-06-11","updatedAt":"2025-06-11T09:30:24.341Z","usuario":"Juan","usuarioEmail":"juanfrauca@outlook.com"},"message":"PRIMARY must be unique","origin":"DB","path":"PRIMARY","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":"TICK-005"}],"fields":{"PRIMARY":"TICK-005"},"level":"error","message":"Error creating ticket: Validation error","name":"SequelizeUniqueConstraintError","original":{"code":"ER_DUP_ENTRY","errno":1062,"parameters":["TICK-005","dasda","dasda","rrhh","Juan","juanfrauca@outlook.com","Media","Abierto","2025-06-11","2025-06-11","[]","2025-06-11 09:30:24","2025-06-11 09:30:24"],"sql":"INSERT INTO `tickets` (`id`,`asunto`,`descripcion`,`departamento`,`usuario`,`usuarioEmail`,`prioridad`,`estado`,`fechaCreacion`,`ultimaActualizacion`,`etiquetas`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);","sqlMessage":"Duplicate entry 'TICK-005' for key 'tickets.PRIMARY'","sqlState":"23000"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"parameters":["TICK-005","dasda","dasda","rrhh","Juan","juanfrauca@outlook.com","Media","Abierto","2025-06-11","2025-06-11","[]","2025-06-11 09:30:24","2025-06-11 09:30:24"],"sql":"INSERT INTO `tickets` (`id`,`asunto`,`descripcion`,`departamento`,`usuario`,`usuarioEmail`,`prioridad`,`estado`,`fechaCreacion`,`ultimaActualizacion`,`etiquetas`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);","sqlMessage":"Duplicate entry 'TICK-005' for key 'tickets.PRIMARY'","sqlState":"23000"},"service":"ticket-service","sql":"INSERT INTO `tickets` (`id`,`asunto`,`descripcion`,`departamento`,`usuario`,`usuarioEmail`,`prioridad`,`estado`,`fechaCreacion`,`ultimaActualizacion`,`etiquetas`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);","stack":"Error\n    at Query.run (/app/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /app/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.insert (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async model.save (/app/node_modules/sequelize/lib/model.js:2490:35)\n    at async Ticket.create (/app/node_modules/sequelize/lib/model.js:1362:12)\n    at async TicketRepository.create (/app/src/repositories/ticket.repository.js:68:12)\n    at async TicketService.createTicket (/app/src/services/ticket.service.js:46:22)\n    at async createTicket (/app/src/controllers/ticket.controller.js:55:22)","timestamp":"2025-06-11T09:30:24.349Z"}
{"ip":"::ffff:172.18.0.1","level":"error","message":"Error al crear el ticket","method":"POST","path":"/api/tickets","service":"ticket-service","stack":"Error: Error al crear el ticket\n    at TicketService.createTicket (/app/src/services/ticket.service.js:63:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async createTicket (/app/src/controllers/ticket.controller.js:55:22)","statusCode":500,"timestamp":"2025-06-11T09:30:24.351Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Access denied for user 'root'@'localhost' (using password: YES)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)","sqlState":"28000"},"service":"ticket-service","stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)\n    at ConnectionManager.connect (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\src\\main.js:86:5)","timestamp":"2025-06-11T10:28:12.935Z"}
{"level":"error","message":"No se pudo conectar a la base de datos: Access denied for user 'root'@'localhost' (using password: YES)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'root'@'localhost' (using password: YES)","sqlState":"28000"},"service":"ticket-service","stack":"SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)\n    at ConnectionManager.connect (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:222:24)\n    at async C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\sequelize.js:305:26\n    at async Sequelize.authenticate (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\node_modules\\sequelize\\lib\\sequelize.js:457:5)\n    at async startServer (C:\\Users\\desarrollos\\Desktop\\Arquitectura-Microservicios\\microservices-project\\ticket-service\\src\\main.js:86:5)","timestamp":"2025-06-11T10:28:31.432Z"}
{"level":"error","message":"Error al enviar correo a it.support@example.com: Missing credentials for \"PLAIN\"","service":"ticket-service","timestamp":"2025-06-11T10:41:51.977Z"}
{"level":"error","message":"Error al enviar correo a it.support@example.com: Missing credentials for \"PLAIN\"","service":"ticket-service","timestamp":"2025-06-11T10:42:20.697Z"}
